# Generated by Django 4.1.7 on 2023-09-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_correctchoice_quizquestion_correct_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='answered_correctly',
        ),
    ]
